version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: cnttvietnhat
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mrtaivietbac@gmail.com
      PGADMIN_DEFAULT_PASSWORD: cnttvietnhat
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
